version: '3.7'
name: argenpesos-backend-production
services:
  argenpesos-backend:
    container_name: argenpesos-backend
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - '8001:8001'
    networks:
      - argenpesos_network
    volumes:
      - ./uploads:/app/uploads

networks:
  argenpesos_network:
